name: "Generate Brand Content"
description: "Generates TypeScript files for brand colors, mission, usage guidelines, typography, and logos from manifest"
inputs:
  version:
    description: "The branding version"
    required: true
  commit:
    description: "The commit SHA from the branding repository"
    required: true
  colors:
    description: "JSON-stringified array of color tokens"
    required: true
  brand-mission:
    description: "Brand mission statement"
    required: true
  usage-guidelines:
    description: "JSON-stringified usage guidelines object"
    required: true
  logos:
    description: "JSON-stringified array of logo objects"
    required: true
  fonts:
    description: "JSON-stringified fonts object"
    required: false
  output-dir:
    description: "Output directory for generated files"
    required: true
runs:
  using: "node20"
  main: "index.js"
