name: "Generate Brand Content"
description: "Generates TypeScript files for brand colors, mission, typography, and logos from manifest"
inputs:
  version:
    description: "The branding version"
    required: true
  commit:
    description: "The commit SHA from the branding repository"
    required: true
  colors:
    description: "JSON-stringified color collection"
    required: true
  brand-mission:
    description: "JSON-stringified localized brand mission entries"
    required: true
  logos:
    description: "JSON-stringified logo collection"
    required: true
  mascot:
    description: "JSON-stringified mascot metadata"
    required: true
  typography:
    description: "JSON-stringified typography collection"
    required: true
  output-dir:
    description: "Output directory for generated files"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        VERSION_INPUT: ${{ inputs.version }}
        COMMIT_INPUT: ${{ inputs.commit }}
        COLORS_INPUT: ${{ inputs.colors }}
        BRAND_MISSION_INPUT: ${{ inputs['brand-mission'] }}
        LOGOS_INPUT: ${{ inputs.logos }}
        MASCOT_INPUT: ${{ inputs.mascot }}
        TYPOGRAPHY_INPUT: ${{ inputs.typography }}
        OUTPUT_DIR_INPUT: ${{ inputs['output-dir'] }}
      with:
        script: |
          const { run } = require('${{ github.action_path }}/index.js');
          await run({ 
            core,
            io,
            version: process.env.VERSION_INPUT,
            commit: process.env.COMMIT_INPUT,
            colors: process.env.COLORS_INPUT,
            brandMission: process.env.BRAND_MISSION_INPUT,
            logos: process.env.LOGOS_INPUT,
            mascot: process.env.MASCOT_INPUT,
            typography: process.env.TYPOGRAPHY_INPUT,
            outputDir: process.env.OUTPUT_DIR_INPUT,
          });
