name: "Generate Brand Content"
description: "Generates TypeScript files for brand colors, mission, typography, and logos from manifest"
inputs:
  version:
    description: "The branding version"
    required: true
  commit:
    description: "The commit SHA from the branding repository"
    required: true
  colors:
    description: "JSON-stringified color collection"
    required: true
  brand-mission:
    description: "JSON-stringified localized brand mission entries"
    required: true
  logos:
    description: "JSON-stringified logo collection"
    required: true
  typography:
    description: "JSON-stringified typography collection"
    required: false
  output-dir:
    description: "Output directory for generated files"
    required: true
runs:
  using: "node20"
  main: "index.js"
