name: "Download Branding Assets"
description: "Downloads and organizes branding assets from the branding repository"
inputs:
  repository:
    description: "The repository where to download the branding artifact from"
    required: true
  artifact-id:
    description: "The artifact ID from the branding repository"
    required: true
  run-id:
    description: "The run ID from the branding repository"
    required: false
  github-token:
    description: "GitHub token to access the branding repository artifact"
    required: true
  logos:
    description: "JSON-stringified logo collection"
    required: true
  mascot:
    description: "JSON-stringified mascot object with path"
    required: true
  logos-dir:
    description: "Directory containing logos"
    required: true
  mascot-dir:
    description: "Directory to place mascot asset"
    required: false
runs:
  using: "composite"
  steps:
    - name: Download branding artifact
      id: download-artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        repository: ${{ inputs.repository }}
        run-id: ${{ inputs.run-id }}
        artifact-ids: ${{ inputs.artifact-id }}
        github-token: ${{ inputs.github-token }}
        path: ${{ runner.temp }}/branding-assets-${{ inputs.run-id }}-${{ inputs.artifact-id }}

    - name: Extract and organize assets
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        DOWNLOADED_PATH: ${{ steps.download-artifact.outputs.path }}
        LOGOS_DIR: ${{ inputs.logos-dir }}
        LOGOS_INPUT: ${{ inputs.logos }}
        MASCOT_INPUT: ${{ inputs.mascot }}
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          core.info(`📦 Processing branding assets`);

          // Copy logos based on paths from manifest
          const logoCollection = JSON.parse(process.env.LOGOS_INPUT);
          const logos = Array.isArray(logoCollection.items) ? logoCollection.items : Array.isArray(logoCollection) ? logoCollection : [];
          for (const logo of logos) {
            await copyAsset(logo.name, logo.path);
          }

          // Copy mascot (if present)
          const mascot = JSON.parse(process.env.MASCOT_INPUT);
          if (mascot) {
             await copyAsset(mascot.name, mascot.path);
          }

          async function copyAsset(name, source) {
            if (!source) {
              return core.setFailed(`Asset path is missing for asset: ${name}`);
            }

            const logosDirBaseFolder = path.basename(process.env.LOGOS_DIR);
            if (!source.startsWith(`${logosDirBaseFolder}/`)) {
              return core.setFailed(`Asset path must start with logos directory: ${source}`);
            }

            const sourcePath = path.join(process.env.DOWNLOADED_PATH, source);

            if (fs.existsSync(sourcePath)) {
              const targetPath = path.join(process.env.LOGOS_DIR, name.replace(`${logosDirBaseFolder}/`, ''));
              const targetDir = path.dirname(targetPath);
              await io.mkdirP(targetDir);
              await io.cp(sourcePath, targetPath);
              core.info(`✓ Copied asset: ${name} (${source})`);
            } else {
              core.setFailed(`Asset file not found: ${name}`);
            }
          }

          core.info(`✓ Successfully organized ${logos.length} logos and 1 mascot`);
