name: "Download Branding Assets"
description: "Downloads and organizes branding assets from the branding repository"
inputs:
  repository:
    description: "The repository where to download the branding artifact from"
    required: true
  artifact-id:
    description: "The artifact ID from the branding repository"
    required: true
  run-id:
    description: "The run ID from the branding repository"
    required: false
  github-token:
    description: "GitHub token to access the branding repository artifact"
    required: true
  logos:
    description: "JSON-stringified logo collection"
    required: true
  mascot:
    description: "JSON-stringified mascot object with path"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download branding artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        repository: ${{ inputs.repository }}
        run-id: ${{ inputs.run-id }}
        artifact-ids: ${{ inputs.artifact-id }}
        github-token: ${{ inputs.github-token }}
        path: /tmp/branding-assets

    - name: Extract and organize assets
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Parse inputs
          const logoCollection = JSON.parse(process.env.LOGOS_INPUT);
          const logos = Array.isArray(logoCollection.items) ? logoCollection.items : Array.isArray(logoCollection) ? logoCollection : [];
          const mascot = JSON.parse(process.env.MASCOT_INPUT);

          core.info(`📦 Processing branding assets`);

          // Create target directories
          const dirs = [
            'application/src/data/brand',
            'application/public/brand/logos',
            'application/public/brand/mascot',
            'application/public/brand/downloads'
          ];

          for (const dir of dirs) {
            await io.mkdirP(dir);
          }

          // Copy logos based on paths from manifest
          for (const logo of logos) {
            const sourcePath = path.join('/tmp/branding-assets', logo.path);
            const targetPath = path.join('application/public/brand', logo.path);
            
            if (fs.existsSync(sourcePath)) {
              const targetDir = path.dirname(targetPath);
              await io.mkdirP(targetDir);
              await io.cp(sourcePath, targetPath);
              core.info(`✓ Copied logo: ${logo.name} (${logo.path})`);
            } else {
              core.setFailed(`Logo file not found: ${logo.path}`);
            }
          }

          // Copy mascot (if present)
          if (mascot && mascot.path) {
            const mascotSource = path.join('/tmp/branding-assets', mascot.path);
            const mascotTarget = path.join('application/public/brand', mascot.path);
            
            if (fs.existsSync(mascotSource)) {
              const targetDir = path.dirname(mascotTarget);
              await io.mkdirP(targetDir);
              await io.cp(mascotSource, mascotTarget);
              core.info(`✓ Copied mascot: ${mascot.name} (${mascot.path})`);
            } else {
              core.setFailed(`Mascot file not found: ${mascot.path}`);
            }
          }

          core.info(`✓ Successfully organized ${logos.length} logos and 1 mascot`);
      env:
        LOGOS_INPUT: ${{ inputs.logos }}
        MASCOT_INPUT: ${{ inputs.mascot }}
