name: 'Download Branding Assets'
description: 'Downloads and organizes branding assets from the branding repository'
inputs:
  artifact-id:
    description: 'The artifact ID from the branding repository'
    required: true
  version:
    description: 'The branding version'
    required: true
  commit:
    description: 'The commit SHA from the branding repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download branding artifact
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: branding-assets-${{ inputs.artifact-id }}
        path: /tmp/branding-assets
        github-token: ${{ github.token }}
        repository: hoverkraft-tech/branding
        run-id: ${{ inputs.artifact-id }}

    - name: Extract and organize assets
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const manifest = JSON.parse(process.env.BRANDING_MANIFEST);
          
          core.info(`📦 Processing branding assets v${process.env.VERSION} (${process.env.COMMIT})`);
          
          // Create target directories
          const dirs = [
            'application/src/data/brand',
            'application/public/brand/logos',
            'application/public/brand/mascot',
            'application/public/brand/downloads'
          ];
          
          dirs.forEach(dir => {
            if (!fs.existsSync(dir)) {
              fs.mkdirSync(dir, { recursive: true });
            }
          });
          
          // Copy logos based on manifest paths
          manifest.logos.forEach(logo => {
            const sourcePath = path.join('/tmp/branding-assets', logo.path);
            const targetPath = path.join('application/public/brand', logo.path);
            
            if (fs.existsSync(sourcePath)) {
              const targetDir = path.dirname(targetPath);
              if (!fs.existsSync(targetDir)) {
                fs.mkdirSync(targetDir, { recursive: true });
              }
              fs.copyFileSync(sourcePath, targetPath);
              core.info(`✓ Copied logo: ${logo.name} (${logo.path})`);
            } else {
              core.setFailed(`Logo file not found: ${logo.path}`);
            }
          });
          
          // Copy mascot (if present)
          if (manifest.mascot && manifest.mascot.path) {
            const mascotSource = path.join('/tmp/branding-assets', manifest.mascot.path);
            const mascotTarget = path.join('application/public/brand', manifest.mascot.path);
            
            if (fs.existsSync(mascotSource)) {
              const targetDir = path.dirname(mascotTarget);
              if (!fs.existsSync(targetDir)) {
                fs.mkdirSync(targetDir, { recursive: true });
              }
              fs.copyFileSync(mascotSource, mascotTarget);
              core.info(`✓ Copied mascot: ${manifest.mascot.name} (${manifest.mascot.path})`);
            } else {
              core.setFailed(`Mascot file not found: ${manifest.mascot.path}`);
            }
          }
          
          // Save manifest for reference
          fs.writeFileSync(
            'application/src/data/brand/manifest.json',
            JSON.stringify(manifest, null, 2)
          );
          core.info('✓ Saved manifest.json');
          core.info(`✓ Successfully organized ${manifest.logos.length} logos and 1 mascot`);
      env:
        VERSION: ${{ inputs.version }}
        COMMIT: ${{ inputs.commit }}
