name: "Download Branding Assets"
description: "Downloads and organizes branding assets from the branding repository"
inputs:
  repository:
    description: "The repository where to download the branding artifact from"
    required: true
  artifact-id:
    description: "The artifact ID from the branding repository"
    required: true
  run-id:
    description: "The run ID from the branding repository"
    required: false
  github-token:
    description: "GitHub token to access the branding repository artifact"
    required: true
  logos:
    description: "JSON-stringified logo collection"
    required: true
  mascot:
    description: "JSON-stringified mascot object with path"
    required: true
  logos-dir:
    description: "Directory containing logos"
    required: true
  mascot-dir:
    description: "Directory to place mascot asset"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download branding artifact
      id: download-artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        repository: ${{ inputs.repository }}
        run-id: ${{ inputs.run-id }}
        artifact-ids: ${{ inputs.artifact-id }}
        github-token: ${{ inputs.github-token }}
        path: ${{ runner.temp }}/branding-assets-${{ inputs.run-id }}-${{ inputs.artifact-id }}

    - name: Extract and organize assets
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        DOWNLOADED_PATH: ${{ steps.download-artifact.outputs.download-path }}
        LOGOS_DIR: ${{ inputs.logos-dir }}
        LOGOS_INPUT: ${{ inputs.logos }}
        MASCOT_INPUT: ${{ inputs.mascot }}
        MASCOT_DIR: ${{ inputs.mascot-dir }}
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          core.debug("Listing downloaded files:");
          const downloadedFiles = fs.readdirSync(process.env.DOWNLOADED_PATH);
          for (const file of downloadedFiles) {
            core.debug(`- ${file}`);
          }

          core.info(`📦 Processing branding assets`);

          // Copy logos based on paths from manifest
          const logoCollection = JSON.parse(process.env.LOGOS_INPUT);
          const logos = Array.isArray(logoCollection.items) ? logoCollection.items : Array.isArray(logoCollection) ? logoCollection : [];
          core.debug(`Logos: ${JSON.stringify(logos, null, 2)}`);

          // Empty dir before copying
          if (fs.existsSync(process.env.LOGOS_DIR)) {
            core.info(`Emptying logos directory: ${process.env.LOGOS_DIR}`);
            await io.rmRF(process.env.LOGOS_DIR);
          }

          for (const logo of logos) {
            await copyAssetFormats(logo.name, logo.formats, process.env.LOGOS_DIR);
          }

          // Empty dir before copying
          if (fs.existsSync(process.env.MASCOT_DIR)) {
            core.info(`Emptying mascot directory: ${process.env.MASCOT_DIR}`);
            await io.rmRF(process.env.MASCOT_DIR);
          }

          // Copy mascot
          const mascot = JSON.parse(process.env.MASCOT_INPUT);
          await copyAssetFormats(mascot.name, mascot.formats, process.env.MASCOT_DIR);

          core.info(`✓ Successfully organized ${logos.length} logos and 1 mascot`);

          async function copyAssetFormats(name, formats, targetRootDir) {
            if (!Array.isArray(formats)) {
              return core.setFailed(`Formats is not an array for asset "${name}": ${formats}`);
            }

            for (const format of formats) {
              await copyAsset(name, format.path, targetRootDir);
            }
          }

          async function copyAsset(name, source, targetRootDir) {
            name = getDisplayName(name);
            if (!source) {
              return core.setFailed(`Asset path is missing for asset "${name}": ${source}`);
            }

            if (!targetRootDir ) {
              return core.setFailed(`Target directory is not defined for asset "${name}".`);
            }

            const baseFolder = path.basename(targetRootDir);
            if (!source.startsWith(`${baseFolder}/`)) {
              return core.setFailed(`Asset path must start with logos directory for asset "${name}": ${source}`);
            }

            const sourcePath = path.join(process.env.DOWNLOADED_PATH, source);

            if (fs.existsSync(sourcePath)) {
              const targetPath = path.join(targetRootDir, source.replace(`${baseFolder}/`, ''));
              const targetDir = path.dirname(targetPath);
              core.info(`Copying asset "${name}" from "${sourcePath}" to "${targetPath}"`);
              await io.mkdirP(targetDir);
              await io.cp(sourcePath, targetPath);
              core.info(`✓ Copied asset: ${name} (${source})`);
            } else {
              throw new Error(`Asset file not found for asset "${name}": ${sourcePath}`);
            }
          }

          function getDisplayName(name) {
            if (typeof name === 'string') {
              return name;
            }

            if (name && typeof name === 'object') {
              return getDisplayName(name.en);
            }
            return 'unknown asset';
          }
