name: "Download Branding Assets"
description: "Downloads and organizes branding assets from the branding repository"
inputs:
  artifact-id:
    description: "The artifact ID from the branding repository"
    required: true
  version:
    description: "The branding version"
    required: true
  commit:
    description: "The commit SHA from the branding repository"
    required: true
  logos:
    description: "JSON-stringified array of logo objects with paths"
    required: true
  mascot:
    description: "JSON-stringified mascot object with path"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download branding artifact
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: branding-assets-${{ inputs.artifact-id }}
        path: /tmp/branding-assets
        github-token: ${{ github.token }}
        repository: hoverkraft-tech/branding
        run-id: ${{ inputs.artifact-id }}

    - name: Extract and organize assets
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Parse inputs
          const logos = JSON.parse(process.env.LOGOS_INPUT);
          const mascot = JSON.parse(process.env.MASCOT_INPUT);
          const version = process.env.VERSION_INPUT;
          const commit = process.env.COMMIT_INPUT;

          core.info(`📦 Processing branding assets v${version} (${commit})`);

          // Create target directories
          const dirs = [
            'application/src/data/brand',
            'application/public/brand/logos',
            'application/public/brand/mascot',
            'application/public/brand/downloads'
          ];

          for (const dir of dirs) {
            await io.mkdirP(dir);
          }

          // Copy logos based on paths from manifest
          for (const logo of logos) {
            const sourcePath = path.join('/tmp/branding-assets', logo.path);
            const targetPath = path.join('application/public/brand', logo.path);
            
            if (fs.existsSync(sourcePath)) {
              const targetDir = path.dirname(targetPath);
              await io.mkdirP(targetDir);
              await io.cp(sourcePath, targetPath);
              core.info(`✓ Copied logo: ${logo.name} (${logo.path})`);
            } else {
              core.setFailed(`Logo file not found: ${logo.path}`);
            }
          }

          // Copy mascot (if present)
          if (mascot && mascot.path) {
            const mascotSource = path.join('/tmp/branding-assets', mascot.path);
            const mascotTarget = path.join('application/public/brand', mascot.path);
            
            if (fs.existsSync(mascotSource)) {
              const targetDir = path.dirname(mascotTarget);
              await io.mkdirP(targetDir);
              await io.cp(mascotSource, mascotTarget);
              core.info(`✓ Copied mascot: ${mascot.name} (${mascot.path})`);
            } else {
              core.setFailed(`Mascot file not found: ${mascot.path}`);
            }
          }

          core.info(`✓ Successfully organized ${logos.length} logos and 1 mascot`);
      env:
        LOGOS_INPUT: ${{ inputs.logos }}
        MASCOT_INPUT: ${{ inputs.mascot }}
        VERSION_INPUT: ${{ inputs.version }}
        COMMIT_INPUT: ${{ inputs.commit }}
