name: "Validate Branding Manifest"
description: "Validates the branding manifest against JSON schema and parses it for use in the workflow"
inputs:
  manifest:
    description: "The manifest JSON string from the repository dispatch event"
    required: true
outputs:
  artifact-id:
    description: "The artifact ID from the manifest"
    value: ${{ steps.parse.outputs.artifact-id }}
  version:
    description: "The branding version from the manifest"
    value: ${{ steps.parse.outputs.version }}
  commit:
    description: "The commit SHA from the branding repository"
    value: ${{ steps.parse.outputs.commit }}
  colors:
    description: "JSON-stringified array of color tokens"
    value: ${{ steps.parse.outputs.colors }}
  brand-mission:
    description: "JSON-stringified localized brand mission entries"
    value: ${{ steps.parse.outputs.brand-mission }}
  usage-guidelines:
    description: "JSON-stringified usage guidelines object"
    value: ${{ steps.parse.outputs.usage-guidelines }}
  logos:
    description: "JSON-stringified array of logo objects"
    value: ${{ steps.parse.outputs.logos }}
  mascot:
    description: "JSON-stringified mascot object"
    value: ${{ steps.parse.outputs.mascot }}
  fonts:
    description: "JSON-stringified fonts object (if present)"
    value: ${{ steps.parse.outputs.fonts }}
  locales:
    description: "JSON-stringified array of locales present in the manifest"
    value: ${{ steps.parse.outputs.locales }}
runs:
  using: "composite"
  steps:
    - name: Validate and parse manifest
      id: parse
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const fs = require('fs');
          const Ajv = require('ajv');
          const addFormats = require('ajv-formats');

          // Parse manifest from input
          const manifest = JSON.parse(process.env.MANIFEST_INPUT);

          // Load and validate against schema
          const schema = JSON.parse(fs.readFileSync('.github/schemas/branding-manifest.schema.json', 'utf8'));

          const ajv = new Ajv();
          addFormats(ajv);

          const validate = ajv.compile(schema);
          const valid = validate(manifest);

          if (!valid) {
            core.setFailed(`Manifest validation failed: ${JSON.stringify(validate.errors, null, 2)}`);
            return;
          }

          core.info('✓ Manifest validation passed');

          // Extract and output all values needed by downstream actions
          core.setOutput('artifact-id', manifest.artifactId || '');
          core.setOutput('version', manifest.version);
          core.setOutput('commit', manifest.commit);
          core.setOutput('colors', JSON.stringify(manifest.colors));
          core.setOutput('brand-mission', JSON.stringify(manifest.brandMission));
          core.setOutput('usage-guidelines', JSON.stringify(manifest.usageGuidelines));
          core.setOutput('logos', JSON.stringify(manifest.logos));
          core.setOutput('mascot', JSON.stringify(manifest.mascot));
          core.setOutput('fonts', manifest.fonts ? JSON.stringify(manifest.fonts) : '{}');

          const locales = Object.keys(manifest.brandMission || {});
          core.setOutput('locales', JSON.stringify(locales));

          core.info(`✓ Exported manifest data: ${manifest.colors.length} colors, ${manifest.logos.length} logos, mission locales: ${locales.join(', ')}`);
      env:
        MANIFEST_INPUT: ${{ inputs.manifest }}
