name: "Validate Branding Manifest"
description: "Validates the branding manifest against JSON schema and parses it for use in the workflow"
inputs:
  manifest:
    description: "The manifest JSON string from the repository dispatch event"
    required: true
outputs:
  version:
    description: "The branding version from the manifest"
    value: ${{ steps.validate.outputs.version }}
  commit:
    description: "The commit SHA from the branding repository"
    value: ${{ steps.validate.outputs.commit }}
  colors:
    description: "JSON-stringified color collection"
    value: ${{ steps.validate.outputs.colors }}
  brand-mission:
    description: "JSON-stringified localized brand mission entries"
    value: ${{ steps.validate.outputs.brand-mission }}
  logos:
    description: "JSON-stringified logo collection"
    value: ${{ steps.validate.outputs.logos }}
  mascot:
    description: "JSON-stringified mascot object"
    value: ${{ steps.validate.outputs.mascot }}
  typography:
    description: "JSON-stringified typography collection (if present)"
    value: ${{ steps.validate.outputs.typography }}
  locales:
    description: "JSON-stringified array of locales present in the manifest"
    value: ${{ steps.validate.outputs.locales }}
runs:
  using: "composite"
  steps:
    - uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@23af54bc615d657aa9c13c472ae701445c1811a6 # 0.17.1
      with:
        working-directory: ${{ github.action_path }}

    - name: Validate manifest
      id: validate
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        NODE_PATH: ${{ github.action_path }}/node_modules
        MANIFEST_INPUT: ${{ inputs.manifest }}
        SCHEMA_PATH: ${{ github.action_path }}/../../schemas/branding-manifest.schema.json
      with:
        script: |
          const { run } = require('${{ github.action_path }}/index.js');
          await run({ core, manifest: process.env.MANIFEST_INPUT, schemaPath: process.env.SCHEMA_PATH });
