name: "Generate Brand PDFs"
description: "Resolves localized brand guideline routes and generates PDFs for each locale"
inputs:
  locales:
    description: "JSON array of locale codes provided by the branding manifest"
    required: true
  default-slug:
    description: "Slug used by the default locale for the brand guidelines page"
    required: true
  routes-file:
    description: "Path to the TypeScript file exporting the localized routes map"
    required: false
    default: application/src/i18n/ui.ts
  base-url:
    description: "Base URL used to build capture URLs (e.g. http://localhost:4321)"
    required: true
  downloads-dir:
    description: "Directory where the generated PDFs should be written"
    required: true
  working-directory:
    description: "Working directory for the application"
    required: true
runs:
  using: "composite"
  steps:
    - uses: hoverkraft-tech/ci-github-nodejs/actions/setup-node@0264395060bbde4ec3276b6dca84f0db828070f3 # 0.17.0
      with:
        working-directory: ${{ github.action_path }}

    - name: Generate brand PDFs
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        NODE_PATH: ${{ github.action_path }}/node_modules
        LOCALES_INPUT: ${{ inputs.locales }}
        DEFAULT_SLUG_INPUT: ${{ inputs.default-slug }}
        ROUTES_FILE_INPUT: ${{ inputs.routes-file }}
        BASE_URL_INPUT: ${{ inputs.base-url }}
        DOWNLOADS_DIR_INPUT: ${{ inputs.downloads-dir }}
        WORKING_DIRECTORY_INPUT: ${{ inputs.working-directory }}
      with:
        script: |
          const { run } = require('${{ github.action_path }}/index.js');
          await run({ 
            core,
            locales: process.env.LOCALES_INPUT,
            defaultSlug: process.env.DEFAULT_SLUG_INPUT,
            routesFile: process.env.ROUTES_FILE_INPUT,
            baseUrl: process.env.BASE_URL_INPUT,
            downloadsDir: process.env.DOWNLOADS_DIR_INPUT,
            workingDirectory: process.env.WORKING_DIRECTORY_INPUT,
            workspace: process.env.GITHUB_WORKSPACE,
          });
