name: "Lightouse CI results to badge"
description: "Generate badge from lighthouse CI results"

inputs:
  links:
    description: "A JSON string with a links to uploaded lighthouse CI results. @see https://github.com/treosh/lighthouse-ci-action#outputs"
    required: true
  manifest:
    description: "A JSON string with a manifest of the lighthouse CI results. @see https://github.com/treosh/lighthouse-ci-action#outputs"
    required: true
  badge_format:
    description: "The markup format for the badge"
    required: false
    default: "html"
  badge_title:
    description: "The title of the badge"
    required: false
    default: "Go to Lighthouse report"
  update_readme:
    description: "Whether to update the README.md file"
    required: false
    default: "true"
  commit_message:
    description: "The commit message for the badge update"
    required: false
    default: "docs: Update Lighthouse badge"

outputs:
  badge:
    description: "The badge markup"
    value: ${{ steps.generate-badge.outputs.badge }}


runs:
  using: "composite"
  steps:
    - id: generate-badge
      uses: actions/github-script@v5
      with:
        script: |
          const { readFileSync, writeFileSync } = require('fs');

          const lighthouseLinks = ${{ inputs.links }};
          const reportUrl = lighthouseLinks[Object.keys(lighthouseLinks)[0]];

          const [{ summary }] = ${{ inputs.manifest }};
          const summaryKeys = Object.keys(summary);
          const sum = summaryKeys.reduce(
            (currentSum, key) => (currentSum += summary[key]),
            0
          );

          const percentage = Math.round((sum / summaryKeys.length) * 100);

          const percentageToColor = (percentage) => {
            if (percentage >= 95) return 'brightgreen';
            if (percentage >= 90) return 'green';
            if (percentage >= 75) return 'yellowgreen';
            if (percentage >= 60) return 'yellow';
            if (percentage >= 40) return 'orange';
            return 'red';
          };

          const color = percentageToColor(percentage);
          const badgeUrl = `https://img.shields.io/badge/Lighthouse-${percentage}%25-${color}?logo=lighthouse`;

          const badgeFormat = `${{ inputs.badge_format }}`;
          let badgeMarkup = '';
          switch(badgeFormat) {
            case 'markdown':
              badgeMarkup = `[![Lighthouse](${badgeUrl})](${reportUrl} "${{ inputs.badge_title }}")`;
              break;
            case 'html':
              badgeMarkup = `<a title="${{ inputs.badge_title }}" href="${reportUrl}" target="_blank"><img alt="Lighthouse" src="${ badgeUrl }" /></a>`;
              break;
            default:
              throw new Error('Unknown badge format');
          }

          core.setOutput('badge', badgeMarkup);

    - id: write-badge
      if: ${{ inputs.update_readme }} == 'true'
      uses: actions/github-script@v5
      with:
        script: |

          # Get readme file content
          const { readFileSync, writeFileSync } = require('fs');
          const { join } = require('path');
          const { context } = require('@actions/github');

          const readmePath = join(process.env.GITHUB_WORKSPACE, 'README.md');
          const readmeContent = readFileSync(readmePath, 'utf8');

          // Get badge markup
          const badgeMarkup = ${{ steps.generate-badge.outputs.badge }};
          const lighthouseBadgeSeparator = '<!-- Lighthouse badge -->';
          const badgeRegex = new RegExp(`(${lighthouseBadgeSeparator})([\\s\\S]*?)(${lighthouseBadgeSeparator})`, 'g');

          // Replace badge markup
          const newReadmeContent = readmeContent.replace(badgeRegex, `$1${badgeMarkup}$3`);

          const readmeContentHasChanged = readmeContent !== newReadmeContent;
          core.setOutput('readme_content_has_changed', readmeContentHasChanged);

          if (readmeContentHasChanged) {
            // Write new readme file content
            writeFileSync(readmePath, newReadmeContent, 'utf8');          
          }

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: steps.write-badge.outputs.readme_content_has_changed == 'true'
      with:
        commit_message: ${{ inputs.commit_message }}