name: "Create Logo Pack"
description: "Creates a ZIP archive of all brand logos"
inputs:
  logos-dir:
    description: "Directory containing logos"
    required: true
  output-file:
    description: "Output ZIP file path"
    required: true
runs:
  using: "composite"
  steps:
    - name: Verify logos exist
      id: verify
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const logosDir = process.env.LOGOS_DIR;

          if (!fs.existsSync(logosDir)) {
            return core.setFailed(`Logos directory not found: ${logosDir}`);
          }

          const files = fs.readdirSync(logosDir).filter(file => {
            const filePath = path.join(logosDir, file);
            return fs.statSync(filePath).isFile();
          });

          if (files.length === 0) {
            return core.setFailed(`No logo files found in: ${logosDir}`);
          }

          core.setOutput('has-logos', 'true');
          core.info(`✓ Found ${files.length} logos in ${logosDir}`);
      env:
        LOGOS_DIR: ${{ inputs.logos-dir }}

    - name: Create logo pack using zip-release
      if: steps.verify.outputs.has-logos == 'true'
      uses: TheDoctor0/zip-release@b57d897cb5d60cb78b51a507f63fa184cfe35554 # v0.7.6
      with:
        type: "zip"
        filename: "${{ inputs.output-file }}"
        directory: "${{ inputs.logos-dir }}"
        path: "."

    - name: Verify ZIP created
      if: steps.verify.outputs.has-logos == 'true'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const fs = require('fs');
          const outputFile = process.env.OUTPUT_FILE;

          if (!fs.existsSync(outputFile)) {
            return core.setFailed(`Failed to create logo pack: ${outputFile}`);
          }

          const stats = fs.statSync(outputFile);
          core.info(`✓ Created logo pack: ${outputFile} (${stats.size} bytes)`);
      env:
        OUTPUT_FILE: ${{ inputs.output-file }}
