name: "Fetch Releases from Hoverkraft Tech Repos"
description: "Fetches releases from all public Hoverkraft Tech repositories within a date range"
inputs:
  since-date:
    description: "Fetch releases since this date (ISO 8601 format)"
    required: true
  until-date:
    description: "Fetch releases until this date (ISO 8601 format)"
    required: true
  github-token:
    description: "GitHub token for API access"
    required: true
outputs:
  releases-data:
    description: "JSON-stringified array of releases data. If no releases are found, this will be null."
    value: ${{ steps.fetch.outputs.releases-data }}
runs:
  using: "composite"
  steps:
    - name: Fetch releases
      id: fetch
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        SINCE_DATE_INPUT: ${{ inputs.since-date }}
        UNTIL_DATE_INPUT: ${{ inputs.until-date }}
        OWNER: ${{ github.repository_owner }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const owner = process.env.OWNER;

          // Parse date range from required inputs
          const sinceDate = new Date(process.env.SINCE_DATE_INPUT);
          const untilDate = new Date(process.env.UNTIL_DATE_INPUT);

          core.info(`Checking for releases from ${sinceDate.toISOString()} to ${untilDate.toISOString()}`);

          // Get all public repos for the organization
          const repos = await github.paginate(github.rest.repos.listForOrg, {
            org: owner,
            type: 'public',
            per_page: 100
          });

          core.info(`Found ${repos.length} public repositories`);

          // Fetch releases for each repo
          const releasesData = [];

          for (const repo of repos) {
            const releases = await github.paginate(github.rest.repos.listReleases, {
              owner,
              repo: repo.name,
              per_page: 100
            });
            
            // Filter releases by date
            const recentReleases = releases.filter(release => {
              const publishedAt = new Date(release.published_at);
              return publishedAt >= sinceDate && publishedAt <= untilDate && !release.draft;
            });
            
            if (recentReleases.length > 0) {
              core.info(`Found ${recentReleases.length} release(s) for ${repo.name}`);
              
              releasesData.push({
                repo: repo.name,
                description: repo.description,
                url: repo.html_url,
                stars: repo.stargazers_count,
                releases: recentReleases.map(r => ({
                  name: r.name,
                  tag: r.tag_name,
                  publishedAt: r.published_at,
                  url: r.html_url,
                  body: r.body
                }))
              });
            }
          }

          if (releasesData.length === 0) {
            core.info('No new releases found in the specified period');
          } else {
            core.info(`Found releases from ${releasesData.length} repositories`);
            core.setOutput('releases-data', JSON.stringify(releasesData));
          }
