name: "Generate Brand PDF"
description: "Generates PDFs from the brand guidelines pages for all supported languages"
inputs:
  working-directory:
    description: "Working directory for the application"
    required: true
  output-directory:
    description: "Output directory for PDF files"
    required: true
  config-file:
    description: "Path to config.yaml file"
    required: true
runs:
  using: "node20"
  main: "index.js"
