name: 'Fetch Branding Assets'
description: 'Fetches branding assets from the @hoverkraft-tech/branding repository'
inputs:
  branding-repo:
    description: 'Branding repository to fetch from'
    required: false
    default: 'hoverkraft-tech/branding'
  branding-ref:
    description: 'Git ref (tag, branch, or commit SHA) to fetch'
    required: false
    default: 'main'
  target-dir:
    description: 'Target directory for branding data'
    required: false
    default: 'application/src/data/brand'
  github-token:
    description: 'GitHub token for authentication'
    required: true
outputs:
  assets-fetched:
    description: 'Whether assets were successfully fetched'
    value: ${{ steps.fetch.outputs.success }}
runs:
  using: 'composite'
  steps:
    - name: Check if branding repo is accessible
      id: check-repo
      shell: bash
      continue-on-error: true
      run: |
        if gh repo view ${{ inputs.branding-repo }} &> /dev/null; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "::warning::Cannot access branding repository '${{ inputs.branding-repo }}'"
        fi
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Fetch branding assets
      id: fetch
      if: steps.check-repo.outputs.exists == 'true'
      shell: bash
      run: |
        echo "Fetching branding assets from ${{ inputs.branding-repo }} at ref ${{ inputs.branding-ref }}"
        
        # Create temporary directory for cloning
        TEMP_DIR=$(mktemp -d)
        
        # Clone the branding repository at specified ref
        git clone --depth 1 --branch ${{ inputs.branding-ref }} \
          https://github.com/${{ inputs.branding-repo }}.git "$TEMP_DIR"
        
        # Create target directories
        mkdir -p ${{ inputs.target-dir }}
        mkdir -p application/public/brand/logos
        mkdir -p application/public/brand/downloads
        mkdir -p application/public/brand/mascot
        
        # Fetch colors.css (brand colors)
        if [ -f "$TEMP_DIR/colors.css" ]; then
          cp "$TEMP_DIR/colors.css" ${{ inputs.target-dir }}/colors.css
          echo "✓ Copied brand colors (colors.css)"
        else
          echo "::warning::colors.css not found in branding repository"
        fi
        
        # Fetch logos from logo/ directory
        if [ -d "$TEMP_DIR/logo" ]; then
          cp -r "$TEMP_DIR/logo/"* application/public/brand/logos/
          echo "✓ Copied brand logos"
        else
          echo "::warning::logo/ directory not found in branding repository"
        fi
        
        # Fetch mascot
        if [ -f "$TEMP_DIR/mascot/mascot.png" ]; then
          cp "$TEMP_DIR/mascot/mascot.png" application/public/brand/mascot/
          echo "✓ Copied mascot"
        else
          echo "::warning::mascot/mascot.png not found in branding repository"
        fi
        
        # Clean up
        rm -rf "$TEMP_DIR"
        
        echo "success=true" >> $GITHUB_OUTPUT
        echo "Branding assets fetched successfully from ${{ inputs.branding-ref }}"
